---
title: "Assignment 4"
author: "Lucas Fox, Cuong Pham Vu"
date: "2/21/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

[Annual Survey of Jails 2018](https://www.icpsr.umich.edu/web/NACJD/series/7/studies)

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
library(janitor)
library(srvyr)
```

## Assignment 4


```{r}
jail <- read_dta("37392-0001-Data.dta")

jail <- jail %>%
  janitor::clean_names()

```

```{r, echo = FALSE}

jail <- jail %>%
   mutate(statenames = case_when(
    state == 1 ~ "AL",
    state == 3 ~ "AZ",
    state == 4 ~ "AR",
    state == 5 ~ "CA",
    state == 6 ~ "CO",
    state == 7 ~ "CT",
    state == 8 ~ "DE",
    state == 9 ~ "DC",
    state == 10 ~ "FL",
    state == 11 ~ "GA",
    state == 13 ~ "ID",
    state == 14 ~ "IL",
    state == 15 ~ "IN",
    state == 16 ~ "IA",
    state == 17 ~ "KS",
    state == 18 ~ "KY",
    state == 19 ~ "LA",
    state == 20 ~ "ME",
    state == 21 ~ "MD",
    state == 22 ~ "MA",
    state == 23 ~ "MI",
    state == 24 ~ "MN",
    state == 25 ~ "MS",
    state == 26 ~ "MO",
    state == 27 ~ "MT",
    state == 28 ~ "NE",
    state == 29 ~ "NV",
    state == 30 ~ "NH",
    state == 31 ~ "NJ",
    state == 32 ~ "NM",
    state == 33 ~ "NY",
    state == 34 ~ "NC",
    state == 35 ~ "ND",
    state == 36 ~ "OH",
    state == 37  ~ "OK",
    state == 38 ~ "OR",
    state == 39 ~ "PA",
    state == 41 ~ "SC",
    state == 42 ~ "SD",
    state == 43 ~ "TN",
    state == 44 ~ "TX",
    state == 45 ~ "UT",
    state == 47 ~ "VA",
    state == 48 ~ "WA",
    state == 49 ~ "WV",
    state == 50 ~ "WI",
    state == 51 ~ "WY"
  ))

jail_svy <- jail %>% 
  as_survey_design(weights = finalwt)

jail_svy <- jail_svy %>%
  mutate(region = case_when (
    state == 20 | state == 21 | state == 22 | state == 30 | state == 31 | state == 33 | state == 39 ~ "Northeast",
   state == 1 | state == 4 | state == 9 | state == 10 | state == 11 | state == 18 | state == 19 |
   state == 25 | state == 34 | state == 41 | state == 43 | state == 47 | state == 49 ~ "Southeast", 
  state == 14 | state == 15 | state == 16 | state == 17 | state == 23 | state == 24 | state == 26 |
   state == 28 | state == 35 |state == 36 | state == 42 | state == 50 ~ "Midwest", 
   state == 3 | state == 32 | state == 37 | state == 44 ~ "Southwest", 
   state == 2 | state == 5 | state == 6 | state == 13 | state == 27 | state == 29 | state == 38 | 
  state == 45 | state == 48 | state == 51 ~ "West"))
```

## Plot 1

```{r}

jail_svy %>%
  group_by(state) %>%
  summarize(totblack = survey_total(black),
         statepop = survey_total(totpop),
         propblack = totblack/statepop,
         statenames = statenames) %>%
  ggplot(mapping = aes(x = statepop, y = propblack, label = statenames)) +
  geom_text(check_overlap = TRUE, size = 3) +
  geom_smooth(color = "light blue", se = FALSE) +
  labs(title = "States with larger jail populations tend to jail more African Americans relatively",
       x = "Total jail population in state",
       y = "Proportion of jail population that is Black",
       caption = "Data from Annual Survey of Jails, 2018") +
  theme_minimal()
```

## Plot 2

```{r}
jail_svy %>%
  mutate(capacity = case_when(
    rated > totpop ~ "Under capacity",
    rated == totpop ~ "At capacity",
    rated < totpop ~ "Over capacity"
  )) %>%
  mutate(indic = 1) %>%
  group_by(capacity, region) %>%
  summarize(n = survey_total(indic)) %>%
  ggplot() +
  geom_col(aes(x = capacity, y = n, fill = capacity)) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  facet_wrap("region") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  labs(title = "Facility capacity by region",
       subtitle = "Majority of facilities are under or over capacity",
       y = "Number of facilities",
       caption = "Data from Annual Survey of Prisons, 2018")


```

## Plot 3

```{r}
jail_svy %>%
  group_by(state) %>%
  summarize(totnon = survey_total(noncitz),
            totpop = survey_total(totpop),
            statenames = statenames,
            region = region,
            totice = survey_total(ice),
            propnoncit = totnon/totpop,
            propice = totice/totpop) %>%
  ggplot() +
  geom_point(aes(x = propice, y = propnoncit), alpha = 0.5) +
  geom_smooth(aes(x = propice, y = propnoncit), method = "lm", color = "light blue") +
  theme_minimal() +
  labs(title = "Relationship between share of non-citizens and share of ICE arrests",
       x = "Share of population being held for ICE",
       y = "Share of population that are non-citizens",
       subtitle = "Jails holding more non-citizens typically hold more inmates for ICE",
       caption = "Data from Annual Survey of Prisons, 2018")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
